#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$application = new Symfony\Component\Console\Application('Kep Installer', '0.0.1');
$application->add(new Kep\Installer\Console\KepCommand());
$application->run();